### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by yooseong11** [yuseong11/numble_senior#1]
## 피그마 링크

[넘블 _ 엑티브 시니어 국민은행 화면 디자인](https://www.figma.com/file/8GvrOCnTO5UPTAz2Hpj5cl/%EB%84%98%EB%B8%94-_-%EC%97%91%ED%8B%B0%EB%B8%8C-%EC%8B%9C%EB%8B%88%EC%96%B4-%EA%B5%AD%EB%AF%BC%EC%9D%80%ED%96%89-%ED%99%94%EB%A9%B4-%EB%94%94%EC%9E%90%EC%9D%B8?node-id=0%3A1)

## 개발 과정

- 환경 설정(*)
    - [x]  eslint
    - [x]  prettier
    - [x]  tsconfig
    - [x] tailwind
- 라우팅(*)
    - [x] react-router-dom 설치
    - [x] 스플래시 페이지, 온보딩 페이지 분리 lazy loading
    - [x] splash에서 몇 초뒤에 onboarding 페이지로 가도록
    - [x] 첫페이지에 splahs가 나오도록
    - [x] loading
- 컴포넌트 디자인(*)
    - [x]  색상, 폰트, radius (rem값 사용) [https://nekocalc.com/px-to-rem-converter](https://nekocalc.com/px-to-rem-converter)
    - [x]  애니메이션 구현
    - [x]  figma 이미지 추출
    - [x] 공통 레이아웃 
    - [x] 다음 버튼
    - [x] 페이지 네이션
- 온보딩 페이지 구현(*)
    - [x]  텍스트 추출
    - [x] 스플래시 
    - [x]  페이지 레이아웃 잡기
    - [x] 애니메이션 적용
- Test
    - [x] cypress
- 최적화 
    - [x] 폰트
    - [x] 이미지
    - [x] 반응형
    - [x] 빌드옵션적용
- build (*)
    - [x] vercel

---

- 회원가입 페이지 구현
